//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleLedgerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOP
    {
        public int BOPId { get; set; }
        public int Price { get; set; }
        public System.DateTime Date { get; set; }
        public string Title { get; set; }
        public string Notes { get; set; }
        public int SubjectId { get; set; }
        public int CompanyId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
